### PR TITLE
Document availablity of Arch Linux package

### PR DESCRIPTION
**Pull request by alerque**

### CODE REVIEW

**Comment by mitchellh** [comment]
Sorry someone else beat you to it. Appreciate it. 😄

**Comment by alerque** [comment]
Not exactly. The somebody else amended an earlier PR with this information *after* this commit and PR were posted and included incorrect information in the process: some of the info was completely wrong as it linked to an AUR package instead of the official one, and that had been deleted by the point the documentation commit was posted. The info was later amended to be *mostly* correct, but the current wording is still a bit misleading. The package in Arch's [extra] repo is not "community maintained", is is maintained by two official Arch Linux packagers. With respect to Arch packaging the AUR is the community maintained "user" repository, but [extra] is official.

**Comment by mitchellh** [comment]
> The package in Arch's [extra] repo is not "community maintained", is is maintained by two official Arch Linux packagers. With respect to Arch packaging the AUR is the community maintained "user" repository, but [extra] is official.

The community in our context is that Ghostty community, rather than the Ghostty maintainers. I can try to reword to make that clear but we're consistent with that for all topics throughout the website (and I think it makes sense given its on the Ghostty website).

**Comment by alerque** [comment]
@mitchellh I understand the project perspective is inverted from distros. I am not suggesting you adopt the distro perspective in wording on your side, but I am suggesting wording it differently so you don't use terms that mean the exact opposite thing than you mean in just a slightly different context. The end user is going to both be a user of the distro as well as a user of the app, so if you say "official" when talking about distro packages you need to either exactly specify the perspective ... or just not say it.

The latter is what I would propose. Please see my follow up PR linked above (#165).

**Pull request closed without merging**
